### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by basarat**

### CODE REVIEW

**Comment by basarat** [comment]
Travis is getting stuck :-/

**Comment by johnnyreilly** [comment]
I can relate

**Comment by basarat** [comment]
Docpad's erroring https://travis-ci.org/DefinitelyTyped/definitelytyped.github.io/builds/166169020#L326 with `Warning: Unexpected characters near "'". Use --force to continue.` 

Think its because of an invalid markdown file but I see no context around which file :-/

**Comment by basarat** [comment]
Removed jshint as it wasn't working for me locally :-/

image

**Comment by basarat** [comment]
> Warning: Unexpected characters near "'".� Use --force to continue.

Found the offending file by painfully deleting file one by one :) Its https://github.com/DefinitelyTyped/definitelytyped.github.io/blob/3ae90b9da7246b7aa441f4e8464be13ab5ce5684/src/documents/guides/contributing.html.md.eco#L3 `title: 'Contribution guide''` (notice the extra `'`). I suspect it only became an error in *recent* version of docpad :rose:

**Comment by basarat** [comment]
Tested the website locally `grunt watch` and it works but 

- Its a bit out of date. Especially since `@types` 
- Docpad is no longer a pleasure to use so probably want to replace it at some point. 

That said its good to go! :rose:

**Pull request merged**
